# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import management_pb2 as management__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in management_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ManagementServiceStub(object):
    """-----------------------------------------------------------------------------
    Service Definition
    -----------------------------------------------------------------------------

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.StartProduction = channel.unary_unary(
                '/casting.management.v1.ManagementService/StartProduction',
                request_serializer=management__pb2.StartProductionRequest.SerializeToString,
                response_deserializer=management__pb2.StartProductionResponse.FromString,
                _registered_method=True)
        self.ListItems = channel.unary_unary(
                '/casting.management.v1.ManagementService/ListItems',
                request_serializer=management__pb2.ListItemsRequest.SerializeToString,
                response_deserializer=management__pb2.ListItemsResponse.FromString,
                _registered_method=True)
        self.AllocateItem = channel.unary_unary(
                '/casting.management.v1.ManagementService/AllocateItem',
                request_serializer=management__pb2.AllocateRequest.SerializeToString,
                response_deserializer=management__pb2.AllocateResponse.FromString,
                _registered_method=True)
        self.PlanRoute = channel.unary_unary(
                '/casting.management.v1.ManagementService/PlanRoute',
                request_serializer=management__pb2.PlanRouteRequest.SerializeToString,
                response_deserializer=management__pb2.PlanRouteResponse.FromString,
                _registered_method=True)
        self.ExecuteCommand = channel.unary_unary(
                '/casting.management.v1.ManagementService/ExecuteCommand',
                request_serializer=management__pb2.ExecuteCommandRequest.SerializeToString,
                response_deserializer=management__pb2.ExecuteCommandResponse.FromString,
                _registered_method=True)
        self.WatchItems = channel.unary_stream(
                '/casting.management.v1.ManagementService/WatchItems',
                request_serializer=management__pb2.WatchItemsRequest.SerializeToString,
                response_deserializer=management__pb2.ItemEvent.FromString,
                _registered_method=True)
        self.WatchAlerts = channel.unary_stream(
                '/casting.management.v1.ManagementService/WatchAlerts',
                request_serializer=management__pb2.WatchAlertsRequest.SerializeToString,
                response_deserializer=management__pb2.AlertEvent.FromString,
                _registered_method=True)
        self.Health = channel.unary_unary(
                '/casting.management.v1.ManagementService/Health',
                request_serializer=management__pb2.Empty.SerializeToString,
                response_deserializer=management__pb2.Empty.FromString,
                _registered_method=True)
        self.GetLatestFrame = channel.unary_unary(
                '/casting.management.v1.ManagementService/GetLatestFrame',
                request_serializer=management__pb2.LatestFrameRequest.SerializeToString,
                response_deserializer=management__pb2.LatestFrameResponse.FromString,
                _registered_method=True)
        self.WatchCameraFrames = channel.unary_stream(
                '/casting.management.v1.ManagementService/WatchCameraFrames',
                request_serializer=management__pb2.WatchFramesRequest.SerializeToString,
                response_deserializer=management__pb2.LatestFrameResponse.FromString,
                _registered_method=True)


class ManagementServiceServicer(object):
    """-----------------------------------------------------------------------------
    Service Definition
    -----------------------------------------------------------------------------

    """

    def StartProduction(self, request, context):
        """Task Manager (work_order + items)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListItems(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AllocateItem(self, request, context):
        """Task Allocator
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PlanRoute(self, request, context):
        """Traffic Manager
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ExecuteCommand(self, request, context):
        """Robot Executor
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def WatchItems(self, request, context):
        """Execution Monitor — server streaming
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def WatchAlerts(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Health(self, request, context):
        """Health
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetLatestFrame(self, request, context):
        """Latest Image Frame (Stage A — PyQt 품질 페이지 실시간 프레임 표시)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def WatchCameraFrames(self, request, context):
        """Stage B — Server streaming (image_sink condvar 기반 push)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ManagementServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'StartProduction': grpc.unary_unary_rpc_method_handler(
                    servicer.StartProduction,
                    request_deserializer=management__pb2.StartProductionRequest.FromString,
                    response_serializer=management__pb2.StartProductionResponse.SerializeToString,
            ),
            'ListItems': grpc.unary_unary_rpc_method_handler(
                    servicer.ListItems,
                    request_deserializer=management__pb2.ListItemsRequest.FromString,
                    response_serializer=management__pb2.ListItemsResponse.SerializeToString,
            ),
            'AllocateItem': grpc.unary_unary_rpc_method_handler(
                    servicer.AllocateItem,
                    request_deserializer=management__pb2.AllocateRequest.FromString,
                    response_serializer=management__pb2.AllocateResponse.SerializeToString,
            ),
            'PlanRoute': grpc.unary_unary_rpc_method_handler(
                    servicer.PlanRoute,
                    request_deserializer=management__pb2.PlanRouteRequest.FromString,
                    response_serializer=management__pb2.PlanRouteResponse.SerializeToString,
            ),
            'ExecuteCommand': grpc.unary_unary_rpc_method_handler(
                    servicer.ExecuteCommand,
                    request_deserializer=management__pb2.ExecuteCommandRequest.FromString,
                    response_serializer=management__pb2.ExecuteCommandResponse.SerializeToString,
            ),
            'WatchItems': grpc.unary_stream_rpc_method_handler(
                    servicer.WatchItems,
                    request_deserializer=management__pb2.WatchItemsRequest.FromString,
                    response_serializer=management__pb2.ItemEvent.SerializeToString,
            ),
            'WatchAlerts': grpc.unary_stream_rpc_method_handler(
                    servicer.WatchAlerts,
                    request_deserializer=management__pb2.WatchAlertsRequest.FromString,
                    response_serializer=management__pb2.AlertEvent.SerializeToString,
            ),
            'Health': grpc.unary_unary_rpc_method_handler(
                    servicer.Health,
                    request_deserializer=management__pb2.Empty.FromString,
                    response_serializer=management__pb2.Empty.SerializeToString,
            ),
            'GetLatestFrame': grpc.unary_unary_rpc_method_handler(
                    servicer.GetLatestFrame,
                    request_deserializer=management__pb2.LatestFrameRequest.FromString,
                    response_serializer=management__pb2.LatestFrameResponse.SerializeToString,
            ),
            'WatchCameraFrames': grpc.unary_stream_rpc_method_handler(
                    servicer.WatchCameraFrames,
                    request_deserializer=management__pb2.WatchFramesRequest.FromString,
                    response_serializer=management__pb2.LatestFrameResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'casting.management.v1.ManagementService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('casting.management.v1.ManagementService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ManagementService(object):
    """-----------------------------------------------------------------------------
    Service Definition
    -----------------------------------------------------------------------------

    """

    @staticmethod
    def StartProduction(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/casting.management.v1.ManagementService/StartProduction',
            management__pb2.StartProductionRequest.SerializeToString,
            management__pb2.StartProductionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListItems(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/casting.management.v1.ManagementService/ListItems',
            management__pb2.ListItemsRequest.SerializeToString,
            management__pb2.ListItemsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AllocateItem(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/casting.management.v1.ManagementService/AllocateItem',
            management__pb2.AllocateRequest.SerializeToString,
            management__pb2.AllocateResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def PlanRoute(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/casting.management.v1.ManagementService/PlanRoute',
            management__pb2.PlanRouteRequest.SerializeToString,
            management__pb2.PlanRouteResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ExecuteCommand(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/casting.management.v1.ManagementService/ExecuteCommand',
            management__pb2.ExecuteCommandRequest.SerializeToString,
            management__pb2.ExecuteCommandResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def WatchItems(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/casting.management.v1.ManagementService/WatchItems',
            management__pb2.WatchItemsRequest.SerializeToString,
            management__pb2.ItemEvent.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def WatchAlerts(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/casting.management.v1.ManagementService/WatchAlerts',
            management__pb2.WatchAlertsRequest.SerializeToString,
            management__pb2.AlertEvent.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Health(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/casting.management.v1.ManagementService/Health',
            management__pb2.Empty.SerializeToString,
            management__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetLatestFrame(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/casting.management.v1.ManagementService/GetLatestFrame',
            management__pb2.LatestFrameRequest.SerializeToString,
            management__pb2.LatestFrameResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def WatchCameraFrames(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/casting.management.v1.ManagementService/WatchCameraFrames',
            management__pb2.WatchFramesRequest.SerializeToString,
            management__pb2.LatestFrameResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class ImagePublisherServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.PublishFrames = channel.stream_unary(
                '/casting.management.v1.ImagePublisherService/PublishFrames',
                request_serializer=management__pb2.ImageFrame.SerializeToString,
                response_deserializer=management__pb2.ImageAck.FromString,
                _registered_method=True)


class ImagePublisherServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def PublishFrames(self, request_iterator, context):
        """Image Publisher → Server: client streaming (서버는 ack 단건 응답)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ImagePublisherServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'PublishFrames': grpc.stream_unary_rpc_method_handler(
                    servicer.PublishFrames,
                    request_deserializer=management__pb2.ImageFrame.FromString,
                    response_serializer=management__pb2.ImageAck.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'casting.management.v1.ImagePublisherService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('casting.management.v1.ImagePublisherService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ImagePublisherService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def PublishFrames(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(
            request_iterator,
            target,
            '/casting.management.v1.ImagePublisherService/PublishFrames',
            management__pb2.ImageFrame.SerializeToString,
            management__pb2.ImageAck.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
